#!/bin/bash

echo -n -e 'enter sketch (i.e. ardurover) : '
read sketch
if [[ $sketch = '' ]]; then
	sketch='ardurover'
fi
echo -e "sketch entered: >>$sketch<<"

avarice --mkII --capture --jtag usb :4242 &
gnome-terminal -x avr-gdb ./build/$sketch.build/$sketch.elf
echo -e '\n\nat the gdb prompt type "target remote localhost:4242"'
